# Generated by Django 5.2.15 on 2026-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
